export const greetings: string[] = [
  "Power",
  "Let's crush it",
  "Auf geht’s, Champion",
  "Topstart in den Tag",
  "Vollgas voraus",
  "Let’s goooo",
  "Peak Performance",
  "Level up",
  "Erfolg beginnt jetzt",
  "High Energy",
  "Push the limit",
  "Winning Mindset",
  "Fokus & Drive",
  "Produktiv wie nie",
  "Stark in den Tag",
  "Powerstart",
  "Let’s dominate",
  "Rise & Grind",
  "Mach dein Ding",
  "Mission: Erfolg",
];

export const motivations: string[] = [
  "Augen zu und durch.",
  "Wird schon schiefgehen.",
  "Is halt so.",
  "Geht nicht, gibt’s nicht.",
  "Muss halt.",
  "Reiß dich zamm.",
  "Jammern macht auch nicht fertig.",
  "Nicht schön, aber selten.",
  "Läuft – zwar rückwärts und bergab, aber läuft.",
  "Kopf hoch, auch wenn der Hals dreckig ist.",
  "Einfach machen, wird schon falsch sein.",
  "Wenig Schlaf, viel erreicht – irgendwann.",
  "Ist nicht einfach, wär sonst ja auch langweilig.",
  "Was drückt, wächst.",
  "Druck formt Diamanten – oder zerbricht halt alles.",
  "Keine Zeit für Pause, der Wahnsinn wartet nicht.",
  "Nur die Harten kommen in den Garten.",
  "Nur wer kämpft, wird auch gestählt.",
  "Wer früh aufsteht, flucht zuerst.",
  "Nur wer rennt, kommt irgendwann an.",
  "Nur wer schwitzt, weiß, wie’s schmeckt.",
  "Nur wer leidet, hat auch Content.",
  "Work smart. Win hard.",
];

export const emojis: string[] = [
  "🔥",
  "⚡️",
  "🚀",
  "💪",
  "🏆",
  "🎯",
  "📈",
  "🧠",
  "🏁",
  "📊",
  "🚨",
  "😎",
];

export const replys: { [key: string]: (...args: string[]) => string } = {
  start: (name: string) => `Danke ${name}, dass du dich für den Dienst angemeldet hast! \n\nDu bekommst ab jetzt jeden Tag um \*5:00 Uhr\* eine Motivation für den Tag. Falls du zwischendurch motivation brauchst, kannst du das jederzeit mit /motivate dir einholen.\n\nMit /stop kannst du dich von diesem Dienst wieder abmelden. \n\nBei Rückfragen oder Bugs, schreibe @philpinsdorf auf Telegram an.`,
  stop: (name: string) => `Vielen Dank ${name}, dass du meinen Dienst verwendet hast. \n\nDu hast hiermit deinen Account \*gelöscht\* und wirst in Zukunft \*keine Benachichtigungen\* mehr bekommen. \n\nFalls du dich doch umentscheiden solltest kannst du jederzeit dich mit /start wieder anmelden.`,
  only_after_start: () => `Du musst diesen Dienst erst mit /start abbonieren!`,
  already_registered: () => `Du hast dich bereits registriert.`,
  already_deleted: () => `Dein Account wurde bereits gelöscht.`,
  code: () => `https://github.com/PhilPinsdorf/MorningMotivationBot`,
  issue: () =>  `Report your bug by creating a new Issue here:\nhttps://github.com/PhilPinsdorf/MorningMotivationBot/issues/new\n\nAlternatively you can write @philpinsdorf on Telegram.`,
}