export const greetings: string[] = [
  "Power",
  "Let's crush it",
  "Auf geht’s, Champion",
  "Topstart in den Tag",
  "Vollgas voraus",
  "Let’s goooo",
  "Peak Performance",
  "Level up",
  "Erfolg beginnt jetzt",
  "High Energy",
  "Push the limit",
  "Winning Mindset",
  "Fokus & Drive",
  "Produktiv wie nie",
  "Stark in den Tag",
  "Powerstart",
  "Let’s dominate",
  "Rise & Grind",
  "Mach dein Ding",
  "Mission: Erfolg",
];

export const motivations: string[] = [
  "Augen zu und durch.",
  "Wird schon schiefgehen.",
  "Geht nicht, gibt’s nicht.",
  "Muss halt.",
  "Was muss, das muss.",
  "Nach der Arbeit ist vor der Arbeit.",
  "Jammern macht auch nicht fertig.",
  "Nicht schön, aber läuft.",
  "Läuft – zwar rückwärts und bergab, aber läuft.",
  "Kopf hoch, auch wenn der Hals dreckig ist.",
  "Aufstehn, Krönchen richten, weiter gehen.",
  "Einfach machen, wird schon falsch sein.",
  "Wenig Schlaf, viel erreicht.",
  "Ist nicht einfach, wär sonst ja auch langweilig.",
  "Druck formt Diamanten – oder zerbricht halt alles.",
  "Keine Zeit für Pause, der Wahnsinn wartet nicht.",
  "Nur die Harten kommen in den Garten.",
  "Nur wer kämpft kann auch gewinnen.",
  "Wer früh aufsteht, flucht zuerst.",
  "Nur wer rennt, kommt irgendwann an.",
  "Nur wer schwitzt, kann von wahrer Arbeit reden.",
  "Nur wer leidet ist ein Gewinner.",
  "Work smart. Win hard.",
  "Lieber viel Meinung als viel Ahnung.",
  "Nachts ist es kälter als draußen.",
  "Ist ja wie aufm Bau, einer macht, alle gucken.",
  "Irgendwo ist immer 4.",
  "Ein Haufen Krümel sind auch ein Brot.",
  "Am Arsch sind die Kälber fett.",
  "Am Ende der Jagd werden die Hasen gezählt.",
  "Wer später bremst ist länger schnell.",
  "Wer bremst verliert.",
  "Nichts wird so heiß gegessen wies gekocht wird.",
  "Arbeit ist die beste Jacke.",
  "Mal verliert man, mal gewinnen die anderen.",
  "Nur die Harten komm in den Garten.",
  "Wer den Cent nicht ehrt ist den Euro nicht wert",
  "Viele Hände, schnelles Ende.",
];

export const emojis: string[] = [
  "🔥",
  "⚡️",
  "🚀",
  "💪",
  "🏆",
  "🎯",
  "📈",
  "🧠",
  "🏁",
  "📊",
  "🚨",
  "😎",
];

export const replys: { [key: string]: (...args: string[]) => string } = {
  start: (name: string) => `Danke ${name}, dass du dich für den Dienst angemeldet hast! \n\nDu bekommst ab jetzt jeden Tag um *5:00 Uhr* eine Motivation für den Tag. Falls du zwischendurch motivation brauchst, kannst du das jederzeit mit /motivate dir einholen.\n\nMit /stop kannst du dich von diesem Dienst wieder abmelden. \n\nBei Rückfragen oder Bugs, schreibe @philpinsdorf auf Telegram an.`,
  stop: (name: string) => `Vielen Dank ${name}, dass du meinen Dienst verwendet hast. \n\nDu hast hiermit deinen Account *gelöscht* und wirst in Zukunft *keine Benachichtigungen* mehr bekommen. \n\nFalls du dich doch umentscheiden solltest kannst du jederzeit dich mit /start wieder anmelden.`,
  only_after_start: () => `Du musst diesen Dienst erst mit /start abbonieren!`,
  already_registered: () => `Du hast dich bereits registriert.`,
  already_deleted: () => `Dein Account wurde bereits gelöscht.`,
  code: () => `https://github.com/PhilPinsdorf/MorningMotivationBot`,
  issue: () =>  `Report your bug by creating a new Issue here:\nhttps://github.com/PhilPinsdorf/MorningMotivationBot/issues/new\n\nAlternatively you can write @philpinsdorf on Telegram.`,
}